export const productsData = { 
    "copypaper": [
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        }
      ],
      "soap": [
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        }
      ],
      "stationary": [
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        }
      ],
      "disposables": [
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        }
      ],
      "misc": [
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        }
      ],
      "printing": [
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://imgur.com/L37Gl7j.png",
        }
      ],
      "officework": [
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "terra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "trident-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "century-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "doubleA-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        },
        {
          "type": "product",
          "name": "spectra-A4",
          "cost": "150",
          "desc": "75gsm copy paper. 300 papers per rem",
          "image": "https://i.imgur.com/1234.png",
        }
      ]
}